Backend/new/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from rest_framework_simplejwt.views import TokenVerifyView
from .views import UserRegisterAPIView,ActivationEmailView, ActivateAccountView,ForgotPasswordAPIView,ResetPasswordAPIView,SendActivationEmailView,AdminRegistrationView, AlumniRegistrationView,ForgotUsernameAPIView,ResetUsernameAPIView
from .serializers import CustomTokenObtainPairSerializer
from .views import CreateStaffUserView

class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer

    
urlpatterns = [
    path(
        'admin/',
        admin.site.urls
        ,
       
        ),
        
    path(
        '', include('newApp.urls')
    ),
   
  
#^ DRF Authentication   

    path('register-admin/', AdminRegistrationView.as_view(), name='register-admin'),
    path('register-alumni/', AlumniRegistrationView.as_view(), name='alumni-registration'),

    # & rest_framework_simple jwt authentication  path
    path('register/', UserRegisterAPIView.as_view(), name='registeruser'),
    path('login/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    
    path('activate-email/', ActivationEmailView.as_view(), name='activate_email'),
    path('activate/<uidb64>/<token>/', ActivateAccountView.as_view(), name='activate_account'),

    path('forgot-password/', ForgotPasswordAPIView.as_view(), name='forgot_password'),
    path('reset-password/<uidb64>/<token>/', ResetPasswordAPIView.as_view(), name='reset_password'),

    path('forgot-username/', ForgotUsernameAPIView.as_view(), name='forgot_username'),
    path('reset-username/<uidb64>/<token>/', ResetUsernameAPIView.as_view(), name='reset_password'),
    
    path('send-activation-email/', SendActivationEmailView.as_view(), name='send_activation_email'),
    path('api/create-staff-user/', CreateStaffUserView.as_view(), name='create-staff-user'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new/urls.py
from django.contrib import admin
from django.urls import include, path
from newApp import alumniView as alumni
from newApp import collegeView as college
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(
        'admin/',
        admin.site.urls
        ,
       
        ),
        
    path(
        '', include('newApp.urls')
    ),
    path(
        'accounts/',
        include('django.contrib.auth.urls')
        ),
    path(
        'accounts/signup/alumni/',
        alumni.SignupView.as_view(),
        name='alumni_signup'
        ),
     path(
        'accounts/signup/student/',
        alumni.StudentSignupView.as_view(),
        name='student_signup'
        ),
    path(
        'accounts/signup/college/',
        college.SignupView.as_view(),
        name='college_signup'
        ),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,BaseUserManager,AbstractBaseUser
from PIL import Image
from django.contrib.auth.models import User
from django.contrib.auth.management.commands import createsuperuser
from django.core.management import CommandError
from django.utils.text import capfirst
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.postgres.fields import ArrayField
import json
COLLEGE_CHOICES = [
    ('SSBT COET, Jalgaon', 'SSBT COET, Jalgaon'),
     
]   
class User(AbstractUser):
    is_alumni = models.BooleanField(default=False,  blank=True)
    is_student = models.BooleanField(default=False, blank=True)
    admin=models.BooleanField(default=False,  blank=True)
    email = models.EmailField(unique=True) 

    College = models.CharField( 
        max_length=80,
        choices=COLLEGE_CHOICES, 
        default="SSBT COET",
        blank=True
    )
    About = models.TextField(max_length=800)        
    Work = models.TextField(max_length=800)
    Year_Joined = models.CharField(max_length=4,  blank=True)
    Branch = models.CharField(max_length=50)
    Image = models.ImageField(
        upload_to='images', 
        default='default/def.jpeg',
        blank=True
    )
    mobile=models.CharField(max_length=10,default='',blank=True)
    linkedin=models.CharField(max_length=100,default='',blank=True)
    Github=models.CharField(max_length=100,default='',blank=True)
    instagram=models.CharField(max_length=100,default='',blank=True)
    skills=models.TextField(default='')
    first_name = models.CharField(max_length=30)  
    last_name = models.CharField(max_length=150)
    followers = models.TextField(default='[]',blank=True)  
    following = models.TextField(default='[]',blank=True)

    def string_to_list(self, string):
        """Converts a string representing a list to a Python list."""
        items = string.strip('[]').split(',')
        items = [item.strip() for item in items if item.strip()]
        return items
    
    def list_to_string(self, lst):
        """Converts a Python list to a string representing a list."""
        str_items = map(str, lst)
        joined_str = ', '.join(str_items)
        return '[' + joined_str + ']'


    def set_followers(self, followers_list):
        stringfollowers_list = self.list_to_string(followers_list)
        self.followers = stringfollowers_list

    def get_followers(self):
        return self.string_to_list(self.followers)

    def set_following(self, following_list):
        stringfollowing_list = self.list_to_string(following_list)
        self.following = stringfollowing_list
        
        
    def get_following(self):
        return self.string_to_list(self.following)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.Image.path)
        if img.height > 500 or img.width > 500:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.Image.path)
        if not self.is_alumni and not self.is_student:
            self.admin=True



class Command(createsuperuser.Command):
    help = 'Custom createsuperuser command'

    def handle(self, *args, **options):
       
        self.stdout.write(self.style.SUCCESS('Custom logic before createsuperuser'))

        
        super().handle(*args, **options)


        self.stdout.write(self.style.SUCCESS('Custom logic after createsuperuser'))

        username = options.get('username', None)
        if username:
            try:
                user = self.UserModel._default_manager.get_by_natural_key(username)
                user.admin = True
                user.save()
                self.stdout.write(self.style.SUCCESS(f'Set admin=True for user {username}'))
            except self.UserModel.DoesNotExist:
                raise CommandError("The user doesn't exist.")




class AlumniPost(models.Model):
    author=models.ForeignKey(User, on_delete=models.CASCADE,default=0)
    tag = models.CharField(max_length=255,default='')
    content = models.TextField(default='')
    title = models.CharField(max_length=255,default='')
    Image = models.ImageField(
        upload_to='images',
        default='default/def.jpeg'
    )
    likes = models.IntegerField(default=0)
  
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.Image.path)
        if img.height > 500 or img.width > 500:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.Image.path)
        

templates/showalumni.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load templatetags %}

{% block content %}
  <style>
    /* Container styles */
    .container-fluid {
      margin-top: 20px;
    }
    
    /* Form styles */
    .col-sm-3 form {
      margin-bottom: 20px;
    }
    
    /* Avatar styles */
    .avatar img {
      height: 150px;
      width: 200px;
    }
    
    /* Card title styles */
    .card-title {
      font-size: 24px;
      margin-bottom: 10px;
    }
    
    /* Text info styles */
    .text-info {
      font-size: 16px;
      margin-bottom: 5px;
    }
    
    /* Pagination styles */
    .pagination {
      margin-left: 100px;
      margin-top: 50px;
    }
    
    .pagination span {
      display: flex;
      justify-content: center;
      align-items: center;
    }
    
    .pagination a {
      margin: 0 5px;
    }
    
    .pagination .disabled {
      cursor: not-allowed;
    }
    
    /* Additional styles for enhanced UI */
    .card {
      background-color: #f8f9fa;
      border-radius: 10px;
      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
      transition: transform 0.3s ease-in-out;
    }
    
    .card:hover {
      transform: scale(1.05);
    }
    
    .card-header img {
      width: 100%;
      height: 200px;
      object-fit: cover;
      border-radius: 10px 10px 0 0;
    }
    
    .card-body {
      padding: 20px;
    }
    
    .card-body h4 {
      font-size: 20px;
      margin-bottom: 10px;
    }
    
    .card-body p {
      font-size: 14px;
      margin-bottom: 20px;
    }
    
    .user {
      display: flex;
      align-items: center;
    }
    
    .user img {
      border-radius: 50%;
      width: 40px;
      height: 40px;
      margin-right: 10px;
    }
    
    .user-info h5 {
      font-size: 16px;
      margin: 0;
    }
    
    .user-info small {
      font-size: 14px;
      color: #777;
    }
    
    button.create-post-btn {
      background-color: #47bcd4;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      margin-bottom: 20px;
    }
    
    button.create-post-btn a {
      text-decoration: none;
      color: #fff;
    }
    .reset-btn {
      color: white;
      background-color: red;
      border-color: red;
      transition: background-color 0.3s, color 0.3s;
    }
    
    .reset-btn:hover {
      background-color: darkred;
      border-color: darkred;
      color: white;
    }
  </style>

  <div class="container-fluid">
    <div class="row">
      {% block filter %}
        <div class="col-sm-3" style="background-color: aliceblue; border-radius: 10px; padding: 20px; margin-top: 25px; margin-bottom: 70px; margin-left: 15px;">
          <form method="get" style="margin-top: 50px;">
            <h4 class="text-center text-danger" style="margin-bottom: 20px;">Filters</h4>
            <hr />
            {{ filter.form|crispy }}
            <br />

            <button class="btn btn-outline-info btn-block create-post-btn" type="submit" id="searchBtn">Search</button>
            <button class="btn btn-outline-info btn-block create-post-btn reset-btn" type="reset">Reset</button>

            <hr />
          </form>
        </div>
      {% endblock %}

      <div class="col-sm-7">
        <h2 class="text-center" style=" margin-top: 20px; margin-bottom: 20px; color: #47bcd4; font-size: 50px; font-weight: bold ; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif ;  border: #47bcd4 5px solid; border-radius: 10px; ">{{ title }} List</h2>
        <div class="row">
          <h4 class="col-sm-6">Total number of {{ title }} : {{ totallength }}</h4>
          <h4 class="col-sm-6">Total filtered number of {{ title }} : {{ totalfiltered }}</h4>
        </div>

        <br />

        {% for p in page_obj %}
          <hr />
          <div style="background-color: aliceblue; border-radius: 10px; box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); transition: transform 0.3s ease-in-out; margin: 10px; padding: 20px;">
            <a href="{% url 'alumni-detail' p.id %}" style="color: black">
              <div class="mx-auto">
                <div class="row">
                  <div class="avatar mx-auto white col-sm-5">
                    <img src="{{ p.Image.url }}" class="rounded mx-auto d-block" style="margin-top: 50px; height: 250px; width: 300px; " />
                  </div>
                  <div class="col-sm-6">
                    <h4 class="card-title text-danger">
                      {{ p.first_name }} {{ p.last_name }} {% if request.user.id == p.id %}
                        (You)
                      {% endif %}
                    </h4>
                    <hr />
                    <p class="text-info">UserName - {{ p.username }}</p>
                    <p class="text-info">Branch - {{ p.Branch }}</p>
                    <p class="text-info">Skills - {{ p.skills|slice:':100' }}......</p>
                    <hr />
                    <div class="btn-group btn-group">
                      <!-- Form for followers button -->
                      <form action="{% url 'followers' p.id %}" method="GET">
                        <button type="submit" class="btn btn-primary">{{ p.get_followers|length }} Followers</button>
                      </form>

                      <!-- Form for following button -->
                      <form action="{% url 'following' p.id %}" method="GET">
                        <button type="submit" class="btn btn-secondary">{{ p.get_following|length }} Following</button>
                      </form>

                      <!-- Form for posts button -->
                      <form action="{% url 'AlumniPosts' p.username %}" method="GET">
                        <button type="submit" class="btn btn-warning">{{ p.alumnipost_set.all|length }} Posts</button>
                      </form>

                      <!-- Form for follow/unfollow button -->
                      {% if not request.user.id == p.id %}
                        <form action="{% url 'follow' p.id %}" method="post">
                          {% csrf_token %}
                          {% if request.user.id|stringformat:'s' in p.get_followers %}
                            <button type="submit" class="btn btn-danger follow-btn">Unfollow</button>
                          {% else %}
                            <button type="submit" class="btn btn-info follow-btn">Follow</button>
                          {% endif %}
                        </form>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
        {% endfor %}
        <div class="pagination-container text-center">
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First" title="First Page">
                  <span aria-hidden="true">&laquo;</span>
                  <span class="sr-only">First</span>
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous" title="Previous Page">
                  <span aria-hidden="true">&lsaquo;</span>
                  <span class="sr-only">Previous</span>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&laquo;</span>
              </li>
              <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&lsaquo;</span>
              </li>
            {% endif %}

            <li class="page-item disabled">
              <span class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
            </li>

            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next" title="Next Page">
                  <span aria-hidden="true">&rsaquo;</span>
                  <span class="sr-only">Next</span>
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last" title="Last Page">
                  <span aria-hidden="true">&raquo;</span>
                  <span class="sr-only">Last</span>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&rsaquo;</span>
              </li>
              <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&raquo;</span>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      const resetButton = document.querySelector('.reset-btn')
      const searchButton = document.getElementById('searchBtn')
      const inputFieldsToClear = ['id_skills', 'id_Branch', 'id_Work', 'id_first_name', 'id_last_name', 'id_About']
    
      resetButton.addEventListener('click', function () {
        inputFieldsToClear.forEach(function (id) {
          document.getElementById(id).value = ''
        })
    
        searchButton.click()
      })
    })
  </script>
{% endblock %}